function bank_worker(protocol, dataset_id, shard_id)
%BANK_WORKER One shard bank from spliced outputs. No deletion. Throws on failure.
    protocol = string(protocol);
    dataset_id = string(dataset_id);
    shard_id = double(shard_id);

    addpath(fullfile(pa_root(),'core'));
    addpath(fullfile(pa_root(),'txrx'));

    % normalize dataset_full + suffix
    prefix = protocol + "_";
    if startsWith(dataset_id, prefix)
        dataset_full = dataset_id;
        suffix = extractAfter(dataset_id, strlength(prefix));
    else
        dataset_full = prefix + dataset_id;
        suffix = dataset_id;
    end

    % map suffix -> bank
    if suffix == "high_run01"
        bank_name = "ota_core_high_run01";
        run_suffix = "high_run01";
        pas = ["PA2","PA3","PA4","PA8"];
    elseif suffix == "pa1_run01"
        bank_name = "ota_pa1_run01";
        run_suffix = "pa1_run01";
        pas = ["PA1"];
    else
        error("BANK_WORKER unknown dataset suffix: %s", suffix);
    end

    fprintf("WORKER BANK | %s | %s | shard %03d | bank=%s\n", protocol, dataset_full, shard_id, bank_name);

    if protocol == "wifi"
        build_ota_bank(bank_name, shard_id, ...
            'run_suffix', run_suffix, ...
            'protocols', "wifi", ...
            'pas', pas, ...
            'mode', "all", ...
            'chunk_n', 8, ...
            'delete_spliced_after_write', false, ...
            'verbose', true);
    elseif protocol == "bluetooth"
        build_ota_bank(bank_name, [], ...
            'run_suffix', run_suffix, ...
            'protocols', "bluetooth", ...
            'bt_shards', shard_id, ...
            'pas', pas, ...
            'mode', "all", ...
            'chunk_n', 8, ...
            'delete_spliced_after_write', false, ...
            'verbose', true);
    elseif protocol == "zigbee"
        build_ota_bank(bank_name, [], ...
            'run_suffix', run_suffix, ...
            'protocols', "zigbee", ...
            'zb_shards', shard_id, ...
            'pas', pas, ...
            'mode', "all", ...
            'chunk_n', 8, ...
            'delete_spliced_after_write', false, ...
            'verbose', true);
    else
        error("Unsupported protocol %s", protocol);
    end

    fprintf("WORKER BANK DONE | %s | %s | shard %03d\n", protocol, dataset_full, shard_id);
end