function resplice_worker(protocol, dataset_id, shard_id)
%RESPICE_WORKER One shard resplice. No deletion. Throws on failure (so -batch exits nonzero).
    protocol = string(protocol);
    dataset_id = string(dataset_id);
    shard_id = double(shard_id);

    addpath(fullfile(pa_root(),'core'));
    addpath(fullfile(pa_root(),'txrx'));

    fprintf("WORKER RESPLICE | %s | %s | shard %03d\n", protocol, dataset_id, shard_id);

    rx_resplice_tape_simple(protocol, dataset_id, shard_id, ...
        'seed_k', 100000, ...
        'seed_radius', 50000, ...
        'search_radius', 500, ...
        'slip_frames', -3:3, ...
        'auto_skip_records', 20, ...
        'auto_skip_search_radius', 500, ...
        'make_png', false, ...
        'delete_ota_after_load', false);

    fprintf("WORKER RESPLICE DONE | %s | %s | shard %03d\n", protocol, dataset_id, shard_id);
end