#!/usr/bin/env python3
"""Apply the official MILCOM 2026 conference template to generated SVG slides.

This is a deterministic post-processing step. It preserves the scientific/body
content generated by build_svg_slides.py, replaces only the slide background and
content-slide title treatment, and removes the redundant title-slide conference
label because the official title background already carries the MILCOM branding.
"""
from __future__ import annotations

from pathlib import Path
import base64
import io
import re
import subprocess
import tempfile
import xml.etree.ElementTree as ET

from PIL import Image, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SLIDES = ROOT / "slides"
TEMPLATE_PDF = ROOT / "assets" / "template" / "milcom26-ppt-template_v1_25feb26_jb.pdf"

W, H = 1920, 1080
MILCOM_NAVY = "#002856"
TITLE_FONT_FAMILY = "Calibri, Arial, sans-serif"
TITLE_X = 56
TITLE_MAX_W = 1100

SVG_NS = "http://www.w3.org/2000/svg"
XLINK_NS = "http://www.w3.org/1999/xlink"
ET.register_namespace("", SVG_NS)
ET.register_namespace("xlink", XLINK_NS)
Q = lambda tag: f"{{{SVG_NS}}}{tag}"
XHREF = f"{{{XLINK_NS}}}href"


def _font_file() -> str:
    # Calibri is the font used by the official template. Carlito is a metrics-
    # compatible Linux fallback when Calibri is unavailable.
    return subprocess.check_output(
        ["fc-match", "-f", "%{file}", "Calibri:style=Bold"], text=True
    ).strip()


FONT_FILE = _font_file()


def _render_template_page(page: int) -> str:
    """Render one official template PDF page to an exact 1920x1080 PNG data URI."""
    if not TEMPLATE_PDF.exists():
        raise FileNotFoundError(f"Missing official MILCOM template PDF: {TEMPLATE_PDF}")

    with tempfile.TemporaryDirectory() as td:
        prefix = Path(td) / f"milcom_template_page_{page}"
        subprocess.run(
            [
                "pdftocairo",
                "-png",
                "-singlefile",
                "-f",
                str(page),
                "-l",
                str(page),
                "-scale-to-x",
                str(W),
                "-scale-to-y",
                str(H),
                str(TEMPLATE_PDF),
                str(prefix),
            ],
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
            text=True,
        )
        png = prefix.with_suffix(".png")
        payload = png.read_bytes()

    with Image.open(io.BytesIO(payload)) as im:
        if im.size != (W, H):
            raise RuntimeError(f"Template render was {im.size}, expected {(W, H)}")

    return "data:image/png;base64," + base64.b64encode(payload).decode("ascii")


def _remove_by_id(root: ET.Element, element_id: str) -> int | None:
    """Remove first descendant with id and return its parent-child index."""
    for parent in root.iter():
        children = list(parent)
        for idx, child in enumerate(children):
            if child.attrib.get("id") == element_id:
                parent.remove(child)
                return idx if parent is root else None
    return None


def _insert_background(root: ET.Element, data_uri: str) -> None:
    # Support repeatable/idempotent use on already-templated SVGs.
    old_index = _remove_by_id(root, "milcom_template_background")
    background_index = _remove_by_id(root, "background")
    insert_at = background_index if background_index is not None else old_index
    if insert_at is None:
        # title, desc, defs normally occupy the first three root children.
        insert_at = min(3, len(root))

    image = ET.Element(
        Q("image"),
        {
            "id": "milcom_template_background",
            "x": "0",
            "y": "0",
            "width": str(W),
            "height": str(H),
            "preserveAspectRatio": "none",
            XHREF: data_uri,
        },
    )
    root.insert(insert_at, image)


def _wrap_title(title: str) -> tuple[list[str], int]:
    """Fit a conclusion title left of the template logos in at most two lines."""
    title = re.sub(r"\s+", " ", title.strip())
    for size in (48, 46, 44, 42, 40, 38):
        font = ImageFont.truetype(FONT_FILE, size)
        words = title.split()
        lines: list[str] = []
        line = ""
        for word in words:
            trial = (line + " " + word).strip()
            if line and font.getlength(trial) > TITLE_MAX_W:
                lines.append(line)
                line = word
            else:
                line = trial
        if line:
            lines.append(line)
        if len(lines) <= 2 and all(font.getlength(x) <= TITLE_MAX_W for x in lines):
            return lines, size
    raise RuntimeError(f"Could not fit title in MILCOM header: {title}")


def _new_title_group(title: str) -> ET.Element:
    lines, size = _wrap_title(title)
    group = ET.Element(Q("g"), {"id": "title_group"})
    text = ET.SubElement(
        group,
        Q("text"),
        {
            "id": "milcom_header_title",
            "x": str(TITLE_X),
            "font-family": TITLE_FONT_FAMILY,
            "font-size": str(size),
            "font-weight": "700",
            "fill": MILCOM_NAVY,
            "text-anchor": "start",
        },
    )

    if len(lines) == 1:
        baselines = [88]
    else:
        baselines = [59, 110]

    for line, y in zip(lines, baselines):
        tspan = ET.SubElement(text, Q("tspan"), {"x": str(TITLE_X), "y": str(y)})
        tspan.text = line
    return group


def _replace_title_group(root: ET.Element, title: str) -> None:
    insertion = _remove_by_id(root, "title_group")
    if insertion is None:
        # Place after the template background when the source lacks a title group.
        insertion = min(4, len(root))
    root.insert(insertion, _new_title_group(title))


def _slide_number(path: Path) -> int:
    m = re.match(r"slide(\d+)_", path.name)
    if not m:
        raise ValueError(f"Unexpected slide filename: {path.name}")
    return int(m.group(1))


def _validate(root: ET.Element, slide_number: int) -> None:
    if root.attrib.get("viewBox") != "0 0 1920 1080":
        raise RuntimeError(f"Slide {slide_number}: unexpected viewBox {root.attrib.get('viewBox')!r}")

    ids = [e.attrib["id"] for e in root.iter() if "id" in e.attrib]
    if len(ids) != len(set(ids)):
        raise RuntimeError(f"Slide {slide_number}: duplicate SVG ids after template integration")
    if "milcom_template_background" not in ids:
        raise RuntimeError(f"Slide {slide_number}: template background missing")
    if slide_number == 1:
        if "conference_tag" in ids:
            raise RuntimeError("Slide 1: redundant conference_tag still present")
    else:
        if "milcom_header_title" not in ids:
            raise RuntimeError(f"Slide {slide_number}: MILCOM header title missing")


def apply(path: Path, title_bg: str, content_bg: str) -> None:
    number = _slide_number(path)
    tree = ET.parse(path)
    root = tree.getroot()

    title_el = root.find(Q("title"))
    if title_el is None or not (title_el.text or "").strip():
        raise RuntimeError(f"{path.name}: missing SVG <title>")
    title = (title_el.text or "").strip()

    _insert_background(root, title_bg if number == 1 else content_bg)

    if number == 1:
        _remove_by_id(root, "conference_tag")
    else:
        _replace_title_group(root, title)

    desc = root.find(Q("desc"))
    if desc is not None:
        desc.text = (
            "Official MILCOM 2026 conference template applied. "
            "Scientific/body content follows SVG_PRODUCTION_SPEC.md."
        )

    _validate(root, number)
    tree.write(path, encoding="utf-8", xml_declaration=False)
    print(f"templated {path.name}")


def main() -> None:
    slide_paths = sorted(SLIDES.glob("slide??_*.svg"))
    if len(slide_paths) != 12:
        raise RuntimeError(f"Expected 12 generated slide SVGs, found {len(slide_paths)}")

    title_bg = _render_template_page(1)
    content_bg = _render_template_page(2)
    for path in slide_paths:
        apply(path, title_bg, content_bg)

    print("MILCOM 2026 template integration complete for 12 SVG slides.")


if __name__ == "__main__":
    main()
