function [x_pkt, info] = bt_gen_packet(payload_seed32, btCfg)
%BT_GEN_PACKET Deterministic single BLE packet waveform (STRICT).

    rs = RandStream("mt19937ar", "Seed", double(payload_seed32));

    % Build deterministic advertising data bytes with same length as cfg hex
    adv_hex_template = char(btCfg.AdvertisingData);
    if mod(numel(adv_hex_template), 2) ~= 0
        error("btCfg.AdvertisingData must be an even-length hex string.");
    end

    nbytes = numel(adv_hex_template) / 2;
    adv_bytes = randi(rs, [0 255], nbytes, 1, "uint8");
    adv_hex = upper(reshape(dec2hex(adv_bytes, 2).', 1, []));

    % STRICT: one PDU construction path only
    try
        cfgLLAdv = bleLLAdvertisingChannelPDUConfig( ...
            PDUType=btCfg.PDUType, ...
            AdvertiserAddress=btCfg.AdvertiserAddress, ...
            AdvertisingData=adv_hex);

        bits = bleLLAdvertisingChannelPDU(cfgLLAdv);

        x = bleWaveformGenerator(bits, ...
            Mode=btCfg.Mode, ...
            ChannelIndex=btCfg.ChannelIndex, ...
            SamplesPerSymbol=btCfg.SamplesPerSymbol, ...
            AccessAddress=btCfg.AccessAddress, ...
            WhitenStatus=btCfg.WhitenStatus, ...
            ModulationIndex=btCfg.ModulationIndex, ...
            PulseLength=btCfg.PulseLength);

    catch ME
        error([ ...
            "BLE packet generation failed via bleLLAdvertisingChannelPDUConfig/" + ...
            "bleLLAdvertisingChannelPDU/bleWaveformGenerator. " + ...
            "Check Bluetooth Toolbox support and cfg fields. Original error:\n%s" ...
        ], ME.message);
    end

    x_pkt = complex(single(real(x)), single(imag(x)));
    x_pkt = x_pkt(:);

    info = struct( ...
        "advertising_data_hex", adv_hex, ...
        "advertising_data_nbytes", nbytes, ...
        "pdu_type", char(btCfg.PDUType), ...
        "channel_index", double(btCfg.ChannelIndex), ...
        "mode", char(btCfg.Mode), ...
        "samples_per_symbol", double(btCfg.SamplesPerSymbol), ...
        "sample_rate_hz", double(btCfg.SampleRate), ...
        "nsamp", numel(x_pkt) ...
    );
end