% buh_capture.m  (CAPTURE ONLY, SEQUENTIAL)

jobs_real = [
    struct("protocol","wifi",      "dataset_id","wifi_high_run01",      "shards",1:20)
    struct("protocol","bluetooth", "dataset_id","bluetooth_high_run01", "shards",1:20)
    struct("protocol","zigbee",    "dataset_id","zigbee_high_run01",    "shards",1:20)

    struct("protocol","wifi",      "dataset_id","wifi_pa1_run01",       "shards",1:5)
    struct("protocol","bluetooth", "dataset_id","bluetooth_pa1_run01",  "shards",1:5)
    struct("protocol","zigbee",    "dataset_id","zigbee_pa1_run01",     "shards",1:5)
];

capture_batch(jobs_real, ...
  'max_capture_attempts', 20, ...
  'max_capture_events', 4, ...
  'min_fill_frac', 0.999, ...
  'pause_between_attempts_s', 5.0, ...
  'skip_if_bank_ok', true, ...
  'skip_if_spliced_ok', true, ...
  'skip_if_ota_ok', true, ...
  'overwrite', false);